# ????
logging:
  file:
    name: ../mygm-log/spring.log
    # ??????size??? size ???????????
    max-size: 256MB
    # ???????????
    max-history: 15
    # ???????????  ?????????????????????
    total-size-cap: 2GB
    # ???????????????
    clean-history-on-start: true
  level:
    root: info